name: CI

on:
  release:
    types: [created]

permissions:
  packages: write # publish package

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
    steps:
      - uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependency
        run: pnpm install --frozen-lockfile

      - name: Publish to NPM Package
        run: pnpm publish --no-git-checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
